### ISSUE TITLE
Display on Linux Ubuntu Machine

### ISSUE THREAD

**Issue by LauraSchoenhals** [mahan-hosseini/AutoGaitA#7]
To access the program, I have to click on the correct color bar at the bottom. There is not a way to expand the window. I am using Ubuntu 22.04.4. The screenshot below is of the first screen that opens after running 'python -m autogaita'.  It works, but is confusing. 

![image](https://github.com/user-attachments/assets/25cf0898-15a6-45d8-9ac8-e1ac1928e3d9)

**Comment by mahan-hosseini** [comment]
Thank you for sharing this!

Are the following windows (the main GUI windows) displayed correctly? You can compare the screenshots included in our documentation if needed. 

If so you could (instead of "python -m autogaita"):
1. Activate the virtual environment 
2. Enter "python" 
3. Enter "import autogaita" 
4. Enter "autogaita.dlc_gui()" or "autogaita.simi_gui()" or "autogaita.group_gui()" 

This should bring you to the main GUIs directly.

**Comment by LauraSchoenhals** [comment]
Thank you, it does seem that all the other windows display correctly. I also tried it on my windows device today and that displays 100% as expected.

**Comment by mahan-hosseini** [comment]
You are welcome! Good to hear that the other windows display well in Linux - I'll try to have a look at the main window under Linux soon.
